export { entity } from "./lib/filter-def";
export type {
    AndFilterDef,
    BooleanFilterDef,
    CommonFilterOptions,
    ContainsFilterDef,
    EqualsFilterDef,
    FilterDef,
    GTEFilterDef,
    GTFilterDef,
    InArrayFilterDef,
    InputForFilterDef,
    IsNotNullFilterDef,
    IsNullFilterDef,
    LTEFilterDef,
    LTFilterDef,
    OrFilterDef,
    PredicateCreator,
    PrimitiveFilterDef,
} from "./lib/filter-def";
